# Generated by Django 4.0.3 on 2022-03-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0043_message_conversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
