# Generated by Django 4.0.3 on 2022-03-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0044_delete_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='colorScheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_color_scheme', to='flickboutique.colorscheme'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='profileBanner',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='profilePicture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='accentColor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='backgroundColor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='productCardColor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='productCardGlowColor1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='productCardGlowColor2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='secondaryTextColor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='textColor',
            field=models.CharField(max_length=20),
        ),
    ]
