# Generated by Django 4.0.3 on 2022-03-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0046_colorscheme_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='profileBanner',
            field=models.ImageField(default='nobanner.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='profilePicture',
            field=models.ImageField(default='noPP.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='accentColor',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='backgroundColor',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='font',
            field=models.CharField(default='Raleway', max_length=64),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='logo',
            field=models.ImageField(default='billbao_logo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='productCardColor',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='productCardGlowColor1',
            field=models.CharField(default='orange', max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='productCardGlowColor2',
            field=models.CharField(default='lightblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='secondaryTextColor',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='textColor',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
