# Generated by Django 4.0.3 on 2022-03-30 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0047_alter_businessinfo_profilebanner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='colorScheme',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='business_color_scheme', to='flickboutique.colorscheme'),
        ),
    ]
