# Generated by Django 4.0.3 on 2022-03-30 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0050_colorscheme_fontname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='colorScheme',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='business_color_scheme', to='flickboutique.colorscheme'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='profileBanner',
            field=models.ImageField(default='nobanner.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='profilePicture',
            field=models.ImageField(default='noPP.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='accentColor',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='backgroundColor',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='font',
            field=models.CharField(default='Raleway', max_length=64),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='fontName',
            field=models.CharField(default='Raleway', max_length=64),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='logo',
            field=models.ImageField(default='billbao_logo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='productCardColor',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='productCardGlowColor1',
            field=models.CharField(default='orange', max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='productCardGlowColor2',
            field=models.CharField(default='lightblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='secondaryTextColor',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='textColor',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
