# Generated by Django 4.0.3 on 2022-03-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickboutique', '0052_alter_businessinfo_colorscheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='totalRatings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='productRating',
            field=models.FloatField(),
        ),
    ]
